[package]
name = "rp2040-lilos"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.4", features = ["inline-asm"] }
cortex-m-rt = { version = "0.7.1" }
lilos = { version = "1.3.0", features = ["systick"] }
panic-halt = "1.0.0"
rp2040-boot2 = "0.3.0"
rp2040-pac = "0.6.0"
