[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "elf2uf2-rs -d"

rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Lexamples/rp2040",
]

[build]
target = "thumbv6m-none-eabi"
